name: better_player_enhanced
description: Advanced video player based on video_player and Chewie. Supports HLS, DASH, DRM, cache, subtitles, PiP, and much more. AndroidX Media3 powered.
version: 1.0.1
homepage: https://github.com/kingace2056/betterplayer
documentation: https://jhomlala.github.io/betterplayer/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  wakelock_plus: ^1.4.0
  meta: ^1.17.0
  flutter_widget_from_html_core: ^0.17.0
  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.5
  collection: ^1.19.1
  xml: ^6.6.1

dev_dependencies:
  lint: ^2.8.0
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sarthak.better_player_enhanced
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin
